### ISSUE TITLE
Basic cube examples not working on WebGL

### ISSUE THREAD

**Issue by mkorpinen** [Unity-Technologies/Addressables-Sample#12]
![image](https://user-images.githubusercontent.com/51988559/60326297-0df5d380-9992-11e9-97b6-ebefa6adcb97.png)

**Comment by dhawalbanker** [comment]
Anyone? It seems like an error related to AsyncOperations. Is this related to "Multithread not supported in WebGL?

@mkorpinen Were you able to find the solution?

**Comment by frbodya** [comment]
hi, someone find solution?

**Comment by dhawalbanker** [comment]
> hi, someone find solution?

I believe the "async" of c# is not working on WebGL. Try to convert it to Coroutines, it should work.

**Comment by VR-Architect** [comment]
I thought I saw in some doc that WebGL is not supported. But could be wrong.

**Comment by frbodya** [comment]
i don't know when it was fixed, because i try as author and then just wait answer) but everything work

**Comment by alffanclub** [comment]
yes, we fixed it in an unrelated change.  This should be all good now.
