### ISSUE TITLE
Addressables.Release/ReleaseInstance don't clear unused assets.

### ISSUE THREAD

**Issue by 123455151** [Unity-Technologies/Addressables-Sample#15]
[There are two problems that confuse me.
1. In SceneLoading project, I set a custom material to  spheres to check ref count in the profiler.When loading spheres,the ref count goes to 4,and there is no ref count after unloading the scene.But it don't clear unused assets until I call Resources.UnloadUnusedAssets() in code manually.This obviously differ to the document which said  "Once a given asset's ref-count is at zero, it will be unloaded."
Here the screenshot is.
![`WACWE7`U$JMC7Q@Y NT~Z4](https://user-images.githubusercontent.com/31527579/62269840-e39ea680-b466-11e9-97fc-8c601dc0ca04.png)
![Q{N41IUA _ZJ(YBP@C R9_C](https://user-images.githubusercontent.com/31527579/62269844-e6010080-b466-11e9-9d0e-e310bc4304a7.png)

2. In my own project ,When I initiate one prefab,which has been set a custom material,its ref count goes to 2,amazing me a lot. I tried Addressables.Release()/ReleaseInstance(),but them both minus ref count by 1,there is still  ref count of 1.
![53DO(FG%CN57XEMG1 VPBQQ](https://user-images.githubusercontent.com/31527579/62269856-ec8f7800-b466-11e9-94df-aab341e8535e.png)
![8P1S@GF}IZHV$S$5 3VGJ81](https://user-images.githubusercontent.com/31527579/62269859-eef1d200-b466-11e9-9bf1-571f8b9886aa.png)

![@ 2N5%~OAU{$ A1BXLR 489](https://user-images.githubusercontent.com/31527579/62269863-f1542c00-b466-11e9-9f0b-51bcca623c50.png)

**Comment by alffanclub** [comment]
for #1, see https://docs.unity3d.com/Packages/com.unity.addressables@1.4/manual/MemoryManagement.html#when-is-memory-cleared

for #2 I'm not sure without more context.  I'd recommend posting that to the forums (https://forum.unity.com/forums/addressables.156/) as it doesn't actually relate to an issue with the samples
