### ISSUE TITLE
Nothing in FilteredRefenrence

### ISSUE THREAD

**Issue by Rafarel** [Unity-Technologies/Addressables-Sample#2]
Hello, I see nothing special in scene FilteredReference.
Is this repo up to date ?
I guess FilteredReference allows to list addressable assets in the drop down list with some criteria like labels ?
Thanks for your great work addressable sounds to be a great feature !

**Comment by alffanclub** [comment]
hmm, I remember doing the work for that, but must have goofed on my git commits.  Will get that fixed up.

**Comment by RunninglVlan** [comment]
This issue can probably be closed now.
https://github.com/Unity-Technologies/Addressables-Sample/commit/28d97585e191cb4a4bddefab5028f7dd4696e0a4#diff-a3e75dac43c3011ccf4bbd15f97737c3
