### ISSUE TITLE
How to manage AddressableGroups by script

### ISSUE THREAD

**Issue by GZLHZ** [Unity-Technologies/Addressables-Sample#22]
With a great amout of assets, I want to manage assets by script instead of creating groups and drag the assets inside by hand.
Please tell me some examples or how to do it.
Thanks

**Comment by alffanclub** [comment]
Take a look at how our GUI is doing things (remember the addressables package itself is open source).  You'll likely want to utilize CreateOrMoveEntry a lot and CreateGroup 
https://docs.unity3d.com/Packages/com.unity.addressables@1.4/api/UnityEditor.AddressableAssets.Settings.AddressableAssetSettings.html

**Comment by alffanclub** [comment]
to clarify, this pointing to the code doesn't mean we won't at some point make a sample with this.  Just closing this issue for the sake of book keeping.  Will revisit the idea of making this sample as we have time.

**Comment by GZLHZ** [comment]
Ok. Thanks
