### ISSUE TITLE
Update a previous build fails every time with the example unity addressables demos

### ISSUE THREAD

**Issue by wirelessdreamer** [Unity-Technologies/Addressables-Sample#23]
Unity: 2019.2.7f2
Addressables: 1.3.3 and 1.3.8

Update a previous build fails every time with the example unity addressables demos

2. How we can reproduce it using the example you attached

Window->asset management->Addressables->groups

Build->update a previous build
point to: AddressableAssetsData\Windows->addressables_content_state.bin

in recent releases of addressables this always fails

tested with both 1.3.3 and 1.3.8 of addressables

Tested with Bundle naming set to: Append Hash, No Hash, and Only Hash. It fails the same way with all 3 settings

Dump:

FileNotFoundException: Library/BuildCache/b1/b1ecc6112fa791c152b4b447d215d591/3a3c198b9b43f5ecb13fd72358de6006/cff6f55b67135de451348b26e8a5b9a8_assets_done_bolt-enemy.bundle_f4d87e80087fef875556e834572f714d does not exist
System.IO.File.Copy (System.String sourceFileName, System.String destFileName, System.Boolean overwrite) (at <599589bf4ce248909b8a14cbe4a2034e>:0)
UnityEditor.Build.Pipeline.Tasks.ArchiveAndCompressBundles.SetOutputInformation (System.String writePath, System.String finalPath, System.String bundleName, UnityEngine.Build.Pipeline.BundleDetails details) (at Library/PackageCache/com.unity.scriptablebuildpipeline@1.5.4/Editor/Tasks/ArchiveAndCompressBundles.cs:204)
UnityEditor.Build.Pipeline.Tasks.ArchiveAndCompressBundles.Run () (at Library/PackageCache/com.unity.scriptablebuildpipeline@1.5.4/Editor/Tasks/ArchiveAndCompressBundles.cs:189)
UnityEditor.Build.Pipeline.BuildTasksRunner.Run (System.Collections.Generic.IList`1[T] pipeline, UnityEditor.Build.Pipeline.Interfaces.IBuildContext context) (at Library/PackageCache/com.unity.scriptablebuildpipeline@1.5.4/Editor/Shared/BuildTasksRunner.cs:50)
UnityEditor.GenericMenu:CatchMenu(Object, String[], Int32) (at C:/buildslave/unity/build/Editor/Mono/GUI/GenericMenu.cs:121)

**Comment by twinankhs** [comment]
It would be great to have the system configuration, processor, graphics card driver version ready for them that is the next info they might need.

**Comment by wirelessdreamer** [comment]
Nvidia 2060
Driver version 441.20
Core i7 9700k

**Comment by twinankhs** [comment]
Ok after I get setup with the envrionment and define the steps to reproduce it on my laptop ( which has the same specs) I will work with them and make a phone call and file an issue with my Intel email address...they will respond right away.




Get Outlook for Android







On Tue, Nov 12, 2019 at 6:30 AM -0800, "Nathanael Anderson" <notifications@github.com> wrote:












Nvidia 2060

Driver version 441.20

Core i7 9700k

**Comment by kirstenpilla** [comment]
Seems like the file path is too long, try moving the project to a different location
