### ISSUE TITLE
Readability issues 

### ISSUE THREAD

**Issue by marwie** [Unity-Technologies/Addressables-Sample#31]
Hello, few ux/readability issues (see screenshot below)

- the labels popup menu is not properly adjusting its size
- the selected row highlight is not setup for pro skin

![image](https://user-images.githubusercontent.com/5083203/79859203-efedd980-83d0-11ea-9ad4-07dc099aec27.png)

**Comment by alffanclub** [comment]
for issues with the addressables package itself, please file a bug against Unity (or you can mention it on the forums, but that may get a little less traction).  This repo just holds the sample projects.
