### ISSUE TITLE
Unity 2019.4.10   Addressables 1.15.1 SyncAddressale Demo

### ISSUE THREAD

**Issue by jonny91** [Unity-Technologies/Addressables-Sample#45]
It is seem to be wrong with above unity versions.
`Exception: Sync Instantiate failed to finish! Cube
SyncAddressables.Instantiate (System.Object key, UnityEngine.Transform parent, System.Boolean instantiateInWorldSpace) (at Assets/SyncAddressables/SyncAddressables.cs:57)
spawner.FixedUpdate () (at Assets/spawner.cs:34)
`

**Comment by VincentSai** [comment]
You need to change "Play Mode Script" to "Sync Fast" on Addressable Groups window,
also need to fix bug on SyncFastModeBuild.cs
```csharp
            var aaContext = new AddressableAssetsBuildContext
            {
                Settings = aaSettings,
                runtimeData = new ResourceManagerRuntimeData(),
                bundleToAssetGroup = null,
                locations = new List<ContentCatalogDataEntry>(),
                providerTypes = new HashSet<Type>() //Add this
            };
```

**Comment by jonny91** [comment]
thx . it works!
