### ISSUE TITLE
 UnloadScene exeption, not unloading

### ISSUE THREAD

**Issue by sasa42** [Unity-Technologies/Addressables-Sample#7]
Unity 2019.1.1f1
Adressables 0.7.5

To reproduce. try add scene example.

https://github.com/Unity-Technologies/Addressables-Sample/blob/master/Basic/Scene%20Loading/Assets/AddScenes.cs

Exception encountered in operation UnityEngine.ResourceManagement.ResourceManager+CompletedOperation`1[UnityEngine.ResourceManagement.ResourceProviders.SceneInstance], result='', status='Failed': Addressables.UnloadScene() - Cannot find handle for scene UnityEngine.ResourceManagement.ResourceProviders.SceneInstance
UnityEngine.AddressableAssets.Addressables:UnloadScene(SceneInstance, Boolean)

https://github.com/Unity-Technologies/Addressables-Sample/blob/master/Basic/Scene%20Loading/Assets/AddScenes.cs

**Comment by sasa42** [comment]
Here the example to reproduce.

Scenes/Foundation

**Comment by sasa42** [comment]
Issue still exists in 
Unity 2019.1.2f1
Adressables 0.8.2

**Comment by ArturoNereu** [comment]
Are you still having this problem? Is working for me.

**Comment by alffanclub** [comment]
with no response, I'll go ahead and close this.  I believe it's fixed now.
